### PR TITLE
Adding working bot

### PR DESCRIPTION
**Pull request by Deadly-Pigg**
(Not actually complete yet, just for when I'm ready)

### CODE REVIEW

**Comment by VictorVictini** [comment]
lgtm

**Comment by mohfez** [comment]
lgtm

**Comment by Deadly-Pigg** [comment]
you guys did NOT check commits💀

**Comment by VictorVictini** [comment]
nah I defos did

**Comment by Deadly-Pigg** [comment]
> nah I defos did

I trust you

**Comment by Deadly-Pigg** [comment]
Just gonna merge since the chain of branches is messing me up 💀

**Comment by VictorVictini** [comment]
lgtm 2.0

**Pull request merged**
